# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define :controller do |config|
	config.vm.hostname = "tgf"
  end

  config.vm.provider :libvirt do |lv|
      lv.uri = 'qemu+unix:///system'
      lv.cpus = 4
      lv.memory = 8192
      lv.boot 'hd'
      #lv.machine_virtual_size = 100100
      lv.management_network_name = "vag-mgmt01"
      lv.management_network_autostart = "true"
      lv.management_network_address = "192.168.120.0/24"
      lv.management_network_autostart = "true"
  end

  config.vm.provision "shell", inline: <<-SHELL
	yum clean all
	yum update -y
	yum install -y epel-release
	yum install -y joe net-tools lsof ntp vim git ansible python-devel zsh zsh-syntax-highlighting python2-pip gcc tmux tcpdump
	pip install --upgrade pip zipp
	systemctl enable ntpd
	systemctl restart ntpd
	sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
	systemctl restart sshd
	#usermod root -p '\$1\$lYJ/EaMg\$KokgHCs2eqrEZ7Nima.Vs1'

	# Install Docker
	cat <<EOF > /etc/yum.repos.d/dockerrepo.repo
[dockerrepo]
baseurl = https://download.docker.com/linux/centos/7/\\\$basearch/stable
gpgcheck = 1
gpgkey = https://download.docker.com/linux/centos/gpg
name = Docker Repository
EOF

	# Install Kubernetes
	cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

	setenforce 0
	sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
	swapoff -a
	cp /etc/fstab /etc/fstab.org
	grep -v swap /etc/fstab.org > /etc/fstab
	cat > /etc/sysctl.d/10-contrail-node.conf << EOF
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
        sysctl --system
	systemctl daemon-reload

	echo "Fix the SSH"
	rm -rf /home/vagrant/.ssh
	mkdir -p /home/vagrant/.ssh
	chmod 0700 /home/vagrant/.ssh
	# The insecure vagrant key to enforce Vagrant to change it on boot
	#curl -k https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub > /home/vagrant/.ssh/authorized_keys
	echo "Add the Vagrant insecure ssh public key"
	cat <<EOF >/home/vagrant/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
EOF
	chmod 0600 /home/vagrant/.ssh/authorized_keys
	cat > ~vagrant/.ssh/config << EOF
TCPKeepAlive yes
ServerAliveInterval 30
StrictHostKeyChecking no
EOF
	chown vagrant.vagrant -R ~vagrant/.ssh

	# Zeroize the disk to make the compression better
	#dd if=/dev/zero of=/EMPTY bs=1M
	#rm -f /EMPTY
  SHELL

#  config.vm.provision "shell", reboot: true

end
