# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define :k1 do |k1|
  end

  config.vm.hostname = "tgf"

  config.vm.provider :libvirt do |lv|
      lv.uri = 'qemu+unix:///system'
      lv.cpus = 4
      lv.memory = 8192
      lv.boot 'hd'
      lv.machine_virtual_size = 100100
      lv.management_network_name = "vag-mgmt01"
      lv.management_network_autostart = "true"
      lv.management_network_address = "192.168.120.0/24"
      lv.management_network_autostart = "true"
  end

  #config.vm.network :public_network, :ip => "192.168.120.123"

  config.vm.provision "shell", inline: <<-SHELL
	yum clean all
	yum update -y
	yum install -y epel-release
	yum install -y joe net-tools lsof ntp vim git ansible python-devel zsh zsh-syntax-highlighting python2-pip gcc tmux tcpdump
	systemctl enable ntpd
	systemctl restart ntpd
	sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
	systemctl restart sshd
	usermod root -p '\$1\$lYJ/EaMg\$KokgHCs2eqrEZ7Nima.Vs1'
	su - vagrant -c 'ssh-keygen -N "" -f ~vagrant/.ssh/id_rsa'
	cat ~vagrant/.ssh/id_rsa.pub >> ~vagrant/.ssh/authorized_keys
	cat > ~vagrant/.ssh/config << EOF
TCPKeepAlive yes
ServerAliveInterval 30
StrictHostKeyChecking no
EOF
	chown vagrant.vagrant ~vagrant/.ssh/config
	fdisk /dev/vda << EOF
p
d
n
p
1

+100G
p
a
p
w
EOF
	partprobe
	xfs_growfs /dev/vda1

	echo "Clone the git repository"
	git clone -b R5.0 http://github.com/Juniper/contrail-ansible-deployer
	chown vagrant.vagrant -R contrail-ansible-deployer

	pip install --upgrade pip zipp

	# Install Docker
	cat > /etc/yum.repos.d/dockerrepo.repo << EOF
[dockerrepo]
baseurl = https://download.docker.com/linux/centos/7/\\\$basearch/stable
gpgcheck = 1
gpgkey = https://download.docker.com/linux/centos/gpg
name = Docker Repository
EOF

	yum install -y --setopt=obsoletes=0 docker-ce-17.03.1.ce-1.el7.centos docker-ce-selinux-17.03.3.ce-1.el7
	systemctl enable docker.service
	systemctl start docker.service

	# Install Kubernetes
	cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

	yum install -y kubelet-1.9.2-0.x86_64
	yum install -y kubeadm-1.9.2-0.x86_64 kubectl-1.9.2-0.x86_64
	systemctl enable kubelet
	systemctl start kubelet

	# Firewall Daemon is not installed anyway, so we don't need this
	#firewall-cmd --permanent --add-port=6443/tcp
	#firewall-cmd --permanent --add-port=2379-2380/tcp
	#firewall-cmd --permanent --add-port=10250/tcp
	#firewall-cmd --permanent --add-port=10251/tcp
	#firewall-cmd --permanent --add-port=10252/tcp
	#firewall-cmd --permanent --add-port=10255/tcp
	#firewall-cmd –-reload

	cat > /etc/sysctl.d/10-contrail-node << EOF
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
	sysctl --system
	setenforce 0
	sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
	sed -i '/swap/d' /etc/fstab
	swapoff -a

# Lets generate base instances.yaml file
	mv contrail-ansible-deployer/config/instances.yaml contrail-ansible-deployer/config/instances.yaml.org
	cat > contrail-ansible-deployer/config/instances.yaml <<EOF
provider_config:
  bms:
    ssh_pwd: vagrant
    ssh_user: vagrant
    ssh_public_key: /home/vagrant/.ssh/id_rsa.pub
    ssh_private_key: /home/vagrant/.ssh/id_rsa
    ntpserver: 64.99.80.121
    domainsuffix: local
instances:
  bms1:
    provider: bms
    ip: X.X.X.X
global_configuration:
  CONTAINER_REGISTRY: opencontrailnightly
  REGISTRY_PRIVATE_INSECURE: True
contrail_configuration:
  CONTRAIL_VERSION: ocata-5.0-20180219195722
  UPGRADE_KERNEL: true
EOF

  SHELL

#  config.vm.provision "shell", reboot: true

end
